#!/usr/bin/env python3
"""Generate a PowerPoint (.pptx) presentation from text input."""
import sys, os

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    if len(sys.argv) < 3:
        print("Usage: python3 generate_pptx.py <input_text_file> <output_path> [title]", file=sys.stderr)
        sys.exit(1)

    text_file, output_path = sys.argv[1], sys.argv[2]
    title = sys.argv[3] if len(sys.argv) > 3 else "Presentation"

    with open(text_file, 'r', encoding='utf-8') as f:
        text = f.read()

    prs = Presentation()
    sw, sh = prs.slide_width, prs.slide_height

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = RGBColor(0xF8, 0xF9, 0xFA)

    txBox = slide.shapes.add_textbox(Inches(1), Inches(2), sw - Inches(2), Inches(1.5))
    tf = txBox.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]; p.text = title; p.font.size = Pt(36); p.font.bold = True
    p.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E); p.font.name = 'Calibri'; p.alignment = PP_ALIGN.CENTER

    subBox = slide.shapes.add_textbox(Inches(1), Inches(3.5), sw - Inches(2), Inches(0.5))
    stf = subBox.text_frame; stf.word_wrap = True
    sp = stf.paragraphs[0]; sp.text = "Generated by RogbaDocForge"
    sp.font.size = Pt(14); sp.font.color.rgb = RGBColor(0xE9, 0x45, 0x60)
    sp.font.name = 'Calibri'; sp.alignment = PP_ALIGN.CENTER

    # Parse text into slides (paragraphs separated by blank lines)
    lines = text.split('\n')
    paragraphs = []; current_para = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if current_para:
                paragraphs.append('\n'.join(current_para)); current_para = []
        else:
            current_para.append(stripped)
    if current_para:
        paragraphs.append('\n'.join(current_para))

    for slide_idx, para_text in enumerate(paragraphs):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

        txBox = slide.shapes.add_textbox(Inches(1), Inches(1.2), sw - Inches(2), sh - Inches(2))
        tf = txBox.text_frame; tf.word_wrap = True

        para_lines = para_text.split('\n')
        for idx, pl in enumerate(para_lines):
            p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
            p.text = pl
            if idx == 0:
                p.font.size = Pt(20); p.font.bold = True
                p.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E); p.space_before = Pt(0)
            else:
                p.font.size = Pt(14); p.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
                p.space_before = Pt(6); p.space_after = Pt(6)
            p.font.name = 'Calibri'

        # Slide number
        numBox = slide.shapes.add_textbox(Inches(1), sh - Inches(0.6), sw - Inches(2), Inches(0.4))
        ntf = numBox.text_frame; ntf.word_wrap = True
        np = ntf.paragraphs[0]; np.text = f"{slide_idx + 1} / {len(paragraphs)}"
        np.font.size = Pt(10); np.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        np.font.name = 'Calibri'; np.alignment = PP_ALIGN.CENTER

    prs.save(output_path)
    print(output_path)
except ImportError as e:
    print(f"Error importing dependencies: {e}", file=sys.stderr); sys.exit(1)
except Exception as e:
    print(f"Error generating PowerPoint: {e}", file=sys.stderr); sys.exit(1)
